// <auto-generated />
namespace Dag11_CodeFirst3__Work.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TestCascade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestCascade));
        
        string IMigrationMetadata.Id
        {
            get { return "201610060706266_TestCascade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
